global:
  access_log: logs/access.log
  error_log: logs/error.log
  pid: logs/pigeon.pid
  log_level: info

servers:
  - name: curvebs
    listen: 127.0.0.1:12000
    enable_tls: true
    tls_cert_file: /curve-manager/cert/server.crt
    tls_key_file: /curve-manager/cert/server.key
    config:
      access.api.enable_check: true
      access.api.expire_seconds: 60
      access.login.expire_seconds: 1800
      enable.multiple.write.user.login: false
      system.log.expiration.days: 30
      system.alert.expiration.days: 30
      curveadm.service.address: 127.0.0.1:11000
      db.sqlite.filepath: /curve-manager/db/curvebs.db
      smtp_address: smtp.163.com
      smtp_port: 465
      smtp_username: username@163.com
      smtp_password: password
